Implementation : Hebergement
dept-info-iut-dijon/Fraudestudio-Aventura-Back-S5C2 pull request #11
Opened 2023-10-19 15:41 UTC by MateoFavard

Controler et service des coordonnees.
Controler et service des regions.
Controler et service des hebergement.

2023-10-19 16:01 UTC, MarcGrandvincent requested changes
j'ai pas l'impression que tu es injecté ton service dans l'Appli, 
Va dans le DependencyInjection.cs de l'appli et ajoute 
services.AddTransient<IHebergementService,HebergementService>();

2023-10-19 17:47 UTC, MateoFavard commented
PR correct

2023-10-20 08:21 UTC, MarcGrandvincent requested changes

2023-10-20 08:21 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Api/Controllers/HebergementController.cs
> +    /// Crée un hebergement.
Créer

2023-10-20 08:21 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Api/Models/Responses/HebergementsResponse.cs
> +public class HebergementsResponse
HebergementResponse

2023-10-20 08:21 UTC, MarcGrandvincent commented
Amand tes commits

2023-10-20 09:19 UTC, MarcGrandvincent commented
Oublie pas de resolve les commentaires une fois que tu les as fixé car sinon je peux pas vérifier si tu as réellement modifier ou non

2023-10-20 09:51 UTC, MarcGrandvincent requested changes

2023-10-20 09:51 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/HebergementServices.cs
> +
?

2023-10-20 09:51 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/HebergementServices.cs
> +        hebergement.Y = y;
Fait le quand tu créés le Dal

2023-10-20 10:05 UTC, MarcGrandvincent approved these changes

2023-10-20 11:38 UTC, merged