Inplémentation identity
dept-info-iut-dijon/Fraudestudio-Aventura-Back-S5C2 pull request #15
Opened 2023-10-20 13:17 UTC by IndorieSama

2023-10-20 13:17 UTC, MarcGrandvincent commented
Squash tes commits

2023-10-20 15:10 UTC, MarcGrandvincent requested changes

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Utilise GetByIdInternal
On a pas besoin de le savoir

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Methode asynchrone GetByIDAsync permettant de renvoyer l'utilisateur par son id
Même remarque que pour les autres fonctions

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Methode Asynchrone Permettant de récuperer toute les person
Même remarque que les autres fonction

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// <returns>List de Person</returns>
La liste des personnes

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Utilise GetByIDAsync
Pas besoin de le savoir

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Methode synchrone permettant de supprimer un utilisateur par sont id
Même remarque que les autres fonction

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Utilisation de GetByIdInternal
Pas besoin de le savoir

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Methode asynchrone permettant de modifier le mots de passe d'une Person
Même remarque que les autres fonctions

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// <param name="pwd">Nouveaux mots de passe de la person</param>
Carrément il a plusieurs nouveaux mot de passe

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// <returns>la person modifié</returns>
modifiée

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +
Enlève

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +            person.PasswordHash = newPwd;
Vérification inutile

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Methode asynchrone permettant de modifier les informations d'une person
Même remarque que les autres fonctions

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// Utilisation de GetByIdInternal
Pas besoin de le savoir

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// <param name="name">Nom de la person (si changer)</param>
Enlève les si changer, même s'ils ont pas changé ils seront quand même passé dans la fonction

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +    /// <returns>La person modifié</returns>
C/C

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +
Enlève

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/PersonService.cs
> +            person.NormalizedEmail = mail;
Les vérifications servent vraiment à rien

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/SampleService.cs
> +
?

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Services/SampleService.cs
> +    public async Task<SampleBl> CreateAsync(String example , CancellationToken cancellationToken)
Ptdr je sais pas pourquoi tu as modifié la classe d'exemple mais du coup tu peux la remettre comme elle était avant

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Entities/PersonDal.cs
> +
?

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Entities/PersonDal.cs
> +    public string Tel { get; set;}
Commentaire

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Models/GroupBL.cs
> +public class GroupBL : IdentityRole
GroupBl

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Models/GroupBL.cs
> +
?

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Models/PersonBL.cs
> +public class PersonBL : IdentityUser
PersonBl

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Domain/Models/PersonBL.cs
> +
?

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Persistence/DbContextCore.cs
> +public class DbContextCore : IdentityDbContext<PersonDal>
Euh je suis pas convaincu là, une fois que tu auras fait toutes les modifs je testerai de mon côté ce que ça fait

2023-10-20 15:10 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Repositories/Fraudestudio.Aventura.Core.Repositories.csproj
> +    <ItemGroup>
C'est quoi ?

2023-10-20 16:57 UTC, MarcGrandvincent commented
Resolve les commentaires quand tu les as fix, et squash tes commits

2023-10-20 17:33 UTC, IndorieSama commented on Fraudestudio.Aventura.Core.Api/Controllers/PersonController.cs
> +    /// <returns>La person trouvé.</returns>
Genre la personne correspondant à l'ID

2023-10-26 09:01 UTC, MarcGrandvincent requested changes

2023-10-26 17:23 UTC, closed without merging