Implémentation de PlaceOfInterest, Coordinate, Region
dept-info-iut-dijon/Fraudestudio-Aventura-Back-S5C2 pull request #27
Opened 2023-11-28 16:28 UTC by AlexandreANSTETT

Test :
Mise en place de tests de création
Mise en place de test de lecture

2023-11-28 17:00 UTC, MarcGrandvincent requested changes

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +
espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    /// Creer un coordonée
Créer une coordonnée. (faut pas oublier le point :) )

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    /// <param name="request">Requette de création de Coordonée</param>
La requette.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    /// Récupere une coordonnée par ses coordonées
Récupère une coordonnée.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    public Task<HttpResponseMessage> CreateCoordinate(CreateCoordinateRequest request);
CreateCoordinateAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    public Task<HttpResponseMessage> GetCoordinateById(int x, int y);
GetCoordinateByIdAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +
espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    /// Créer un lieu d'interret
Créer un lieu d'intérêt.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    /// <param name="request">Requette de création du lieux d'interret</param>
La requette.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    public Task<HttpResponseMessage> CreatePlaceOfInterest(CreatePlaceOfInterestRequest request);
CreatePlaceOfInterestAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    /// Vérifie qu'on récupere bien tout les lieux d'intéret
Récupère tous les lieux d'intérêt.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    public Task<HttpResponseMessage> GetAllPlaceOfInterest();
GetAllPlaceOfInterestAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    /// Vérifie qu'on récupere le bon lieu d'intéret correspondant à l'identifiant
Récupère un lieu d'intérêt.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    /// <param name="request">Requette de récupération du lieu d'interet</param>
La requête.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/PlaceOfInterest/PlaceOfInterestContext.cs
> +    public Task<HttpResponseMessage> GetPlaceOfInterestById(int id);
GetPlaceOfInterestByIdAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    /// <param name="request">La requette de création de region</param>
La requette.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    public Task<HttpResponseMessage> CreateRegion(CreateRegionRequest request);
CreateRegionAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    /// Récupere toute les région
Récupère toutes les régions.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    public Task<HttpResponseMessage> GetAllRegion();
GetAllRegionAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +
Espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    /// Recupere une region par son identifiant
Récupère une région.

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Context/Region/RegionContext.cs
> +    public Task<HttpResponseMessage> GetRegionById(int id);
GetRegionByIdAsAuthentificated

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/CreateCoordinateTest.cs
> +
Espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/CreateCoordinateTest.cs
> +    [Fact(DisplayName = "00 - Positif - Context"), TestPriority(1)]
00 - Contexte

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/CreateCoordinateTest.cs
> +                X = 10,
Tu voulais pas faire une refacto pour les coordonnées ? je pense que c'est le bon moment de la faire

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +
Espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +public class readCoordinateTest : BaseTest
ReadCoordinateTest

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +    [Fact(DisplayName = "01 - Positif - Context"), TestPriority(1)]
00 - Contexte

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +            return _regionContext.CreateRegion(region);
Tu as oublié le AsScenarioUser()

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +            return _coordinateContext.CreateCoordinate(coordinate);
Tu as oublié le AsScenarioUser()

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +            return _coordinateContext.CreateCoordinate(coordinate);
Tu as oublié le AsScenarioUser()

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +    [Fact(DisplayName = "02 - Récupère la coordonnées par ses ids"), TestPriority(2)]
01 - Consultation d'une coordonnée

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +
Espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +            return _coordinateContext.AsScenarioUser().GetCoordinateById(10,11);
Utilise directement expected.X et expected.Y

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +             return _coordinateContext.AsScenarioUser().GetCoordinateById(12,11);
idem

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +        IsSuccessAsync(() =>
Si c'est un test de consultation il faut utlise IsTheSame(), pas success

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Coordinate/readCoordinateTest.cs
> +         IsSuccessAsync(() =>
idem ici

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/CreatePlaceOfInterestTest.cs
> +
Espace en trop

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/CreatePlaceOfInterestTest.cs
> +    [Fact(DisplayName = "01 - Positif - Context"), TestPriority(1)]
00 - Contexte

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/CreatePlaceOfInterestTest.cs
> +            var placeRequest = new CreatePlaceOfInterestRequest
placeOfInterestRequest

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/ReadPlaceOfInterestTest.cs
> +    [Fact(DisplayName = "00 - Positif - Contexte"), TestPriority(1)]
00 - Contexte

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Region/ReadRegionTest.cs
> +            var reg1 = new CreateRegionRequest
region

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Region/ReadRegionTest.cs
> +            var reg2 = new CreateRegionRequest
region

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/ReadPlaceOfInterestTest.cs
> +    [Fact(DisplayName = "02 - Positif - Récupération d'un lieux d'intéret via son identifiant"), TestPriority(3)]
02 - Positif - Consultation d'un lieu d'intérêt

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Region/ReadRegionTest.cs
> +        await IsTheSame( ()=>_regionContext.AsScenarioUser().GetAllRegion(), expected);
problème d'espace (CTRL + K + D)

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Region/ReadRegionTest.cs
> +            Id = 1,
Met pas l'ID si tu l'ignore

2023-11-28 17:00 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/Region/ReadRegionTest.cs
> +    [Fact(DisplayName = "02 - Positif - Récupere une region par son Id"), TestPriority(3)]
02 - Positif - Consultation d'une région

2023-11-28 17:26 UTC, AlexandreANSTETT commented on Fraudestudio.Aventura.Core.Test/Context/Coordinate/CoordinateContext.cs
> +    /// Creer un coordonée
:)

2023-11-28 17:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/Scenarios/PlaceOfInterest/ReadPlaceOfInterestTest.cs
> +    [Fact(DisplayName = "01 - Positif - Récupération de tout les lieux d'interet"), TestPriority(2)]
Oui

2023-11-29 10:30 UTC, MarcGrandvincent requested changes

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Api/Controllers/CoordinateController.cs
> +    /// Récupère une coordonneé par son ID.
La doc est pas bonne

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Api/Models/Responses/PlaceOfInterestResponse.cs
> +    public int CoordinateId { get; set; }
L'ID sera déjà dans le coordinateResponse, pas besoin de la mettre

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Application/Contracts/ICoordinateService.cs
> +
Trop d'espace

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Persistence/Configurations/CoordinateConfiguration.cs
>              );
Les attributs X et Y sont pas ajouté dans la configuration,.

Rajoute : builder.HasIndex(u => new { u.X, u.Y }).IsUnique();

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/ApiRoutesTest.cs
> +        public const string GetById = BaseRoute + "{id:int}/";
{0}

2023-11-29 10:30 UTC, MarcGrandvincent commented on Fraudestudio.Aventura.Core.Test/ApiRoutesTest.cs
> +        public const string GetById = BaseRoute + "{id:int}/";
{0}

2023-11-29 10:48 UTC, merged